import type { InterviewQuestion } from "@/lib/mocksy/types";

export const QUESTION_BANK: InterviewQuestion[] = [
  { id: "q-001", category: "pre-cas", prompt: "Why did you choose the UK for your higher education?" },
  { id: "q-002", category: "pre-cas", prompt: "Why this university — what stood out compared to other options?" },
  { id: "q-003", category: "pre-cas", prompt: "Why this course — how does it match your academic background?" },
  { id: "q-004", category: "pre-cas", prompt: "What modules are you most excited about, and why?" },
  { id: "q-005", category: "pre-cas", prompt: "How does this course support your long-term career goals?" },
  { id: "q-006", category: "pre-cas", prompt: "What research have you done about employability outcomes for graduates?" },
  { id: "q-007", category: "pre-cas", prompt: "Who are the key faculty or research groups you noticed in the department?" },
  { id: "q-008", category: "pre-cas", prompt: "What academic skills do you expect to strengthen during this degree?" },
  { id: "q-009", category: "pre-cas", prompt: "Describe a project or assignment that prepared you for postgraduate study." },
  { id: "q-010", category: "pre-cas", prompt: "What is your dissertation or thesis topic (if applicable), and why is it important?" },
  { id: "q-011", category: "pre-cas", prompt: "How will you manage the transition to UK academic expectations (reading, writing, referencing)?" },
  { id: "q-012", category: "pre-cas", prompt: "What is your study plan for the first semester?" },
  { id: "q-013", category: "pre-cas", prompt: "How do you plan to use university support services (library, writing centre, careers)?" },
  { id: "q-014", category: "pre-cas", prompt: "What are your strategies for time management and meeting deadlines?" },
  { id: "q-015", category: "pre-cas", prompt: "How will you maintain academic integrity and avoid plagiarism?" },
  { id: "q-016", category: "pre-cas", prompt: "What is your contingency plan if you struggle academically?" },
  { id: "q-017", category: "ukvi", prompt: "What is the purpose of your visit to the UK?" },
  { id: "q-018", category: "ukvi", prompt: "How long do you intend to stay in the UK?" },
  { id: "q-019", category: "ukvi", prompt: "Where will you live, and have you confirmed accommodation?" },
  { id: "q-020", category: "ukvi", prompt: "Who is funding your studies — and can you explain the funding breakdown?" },
  { id: "q-021", category: "ukvi", prompt: "What is your tuition fee for the year, and what have you paid so far?" },
  { id: "q-022", category: "ukvi", prompt: "How much money do you have available for living costs, and for how long will it last?" },
  { id: "q-023", category: "ukvi", prompt: "Do you have a credible bank statement or financial guarantee — what does it show?" },
  { id: "q-024", category: "ukvi", prompt: "Are you planning to work part-time? How will that affect your studies?" },
  { id: "q-025", category: "ukvi", prompt: "What are your plans after completing your course?" },
  { id: "q-026", category: "ukvi", prompt: "Do you intend to return to your home country? Why or why not?" },
  { id: "q-027", category: "ukvi", prompt: "How does this qualification improve your career prospects at home?" },
  { id: "q-028", category: "ukvi", prompt: "Have you travelled internationally before? Tell me about a trip." },
  { id: "q-029", category: "ukvi", prompt: "Do you have relatives or friends in the UK? How will you stay connected with family?" },
  { id: "q-030", category: "ukvi", prompt: "What do you know about UK immigration rules for students?" },
  { id: "q-031", category: "ukvi", prompt: "What would you do if your visa application faced delays?" },
  { id: "q-032", category: "general", prompt: "Tell me about yourself in the context of your studies and goals." },
  { id: "q-033", category: "general", prompt: "What is your greatest academic strength — can you give an example?" },
  { id: "q-034", category: "general", prompt: "Describe a challenge you overcame during your education." },
  { id: "q-035", category: "general", prompt: "How do you handle feedback and improve after a poor grade?" },
  { id: "q-036", category: "general", prompt: "Describe a time you worked in a team. What was your role?" },
  { id: "q-037", category: "general", prompt: "How do you stay organised when you have multiple deadlines?" },
  { id: "q-038", category: "general", prompt: "What are your hobbies, and how do you balance them with study?" },
  { id: "q-039", category: "general", prompt: "Why should the university believe you are a genuine student?" },
  { id: "q-040", category: "general", prompt: "What will you do if your course is harder than expected?" },
  { id: "q-041", category: "pre-cas", prompt: "What alternatives did you consider if you did not get this offer?" },
  { id: "q-042", category: "pre-cas", prompt: "How did you decide between a taught programme and research-focused study?" },
  { id: "q-043", category: "pre-cas", prompt: "What academic resources (journals, labs, software) will you use most?" },
  { id: "q-044", category: "pre-cas", prompt: "Describe how your undergraduate training connects to this programme’s learning outcomes." },
  { id: "q-045", category: "pre-cas", prompt: "What ethical considerations matter in your field of study?" },
  { id: "q-046", category: "ukvi", prompt: "Can you explain your CAS details at a high level (course, dates, sponsor) without memorising incorrectly?" },
  { id: "q-047", category: "ukvi", prompt: "What is your current occupation, and how does it relate to your studies?" },
  { id: "q-048", category: "ukvi", prompt: "Have you ever had a visa refusal? If yes, what happened and what changed?" },
  { id: "q-049", category: "ukvi", prompt: "What health or insurance arrangements have you made for the UK?" },
  { id: "q-050", category: "ukvi", prompt: "How will you travel from the airport to your accommodation on arrival?" },
  { id: "q-051", category: "general", prompt: "What does ‘cultural adaptation’ mean to you, and how will you approach it?" },
  { id: "q-052", category: "general", prompt: "How do you evaluate sources and avoid misinformation in your field?" },
  { id: "q-053", category: "general", prompt: "Tell me about a time you had to learn something quickly. What was your method?" },
  { id: "q-054", category: "pre-cas", prompt: "What professional networks or communities do you hope to join as a student?" },
  { id: "q-055", category: "pre-cas", prompt: "How will you measure whether you are progressing academically each month?" },
  { id: "q-056", category: "ukvi", prompt: "If asked, can you clearly state your course start date and end date?" },
  { id: "q-057", category: "ukvi", prompt: "What are your living expenses estimates for rent, food, and transport?" },
  { id: "q-058", category: "general", prompt: "What questions do you have for the university about support and onboarding?" },
];
